### ISSUE TITLE
Unable to chain factory.onCreate

### ISSUE THREAD

**Issue by hellowodl** [mfellner/valtio-factory#1]
In order to clean up my subscriptions in a way that's as clean as possible, I'd like to be able to chain `factory.onCreate`.

Currently this is impossible to do.
The `factory.onCreate` will always be the only function that gets called in the stack.

**Comment by mfellner** [comment]
Thanks for the issue!

Chaining onCreate currently doesn’t work as expected and leads to previously added callbacks being replaced.

This is because the factory stores only a single callback instead of an array.

Should be pretty easy to implement. Feel free to send a PR, or I’ll try to get it done when I have some time.
